### ISSUE TITLE
infograb error

### ISSUE THREAD

**Issue by whoami-www** [moom825/xeno-rat#66]
![image](https://github.com/user-attachments/assets/d02242c1-249e-46a5-997e-47df693c9990)

Using the infograb function causes rat to crash

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.MemoryStream.InternalReadInt32()
   at System.IO.BinaryReader.ReadInt32()
   at xeno_rat_server.Forms.InfoGrab.DeserializeCookieList(Byte[] bytes)
   at xeno_rat_server.Forms.InfoGrab.<button3_Click>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
xeno rat server
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/attack/Desktop/tools/xeno/xeno%20rat%20server.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
MaxMind.GeoIP2
    Assembly Version: 4.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/attack/Desktop/tools/xeno/xeno%20rat%20server.exe
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
MaxMind.Db
    Assembly Version: 4.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/attack/Desktop/tools/xeno/xeno%20rat%20server.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/attack/Desktop/tools/xeno/xeno%20rat%20server.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by cipiripi84** [comment]
> ![image](https://github.com/user-attachments/assets/d02242c1-249e-46a5-997e-47df693c9990)
> 
> Using the infograb function causes rat to crash
> 
> See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text ************** System.IO.EndOfStreamException: Unable to read beyond the end of the stream. at System.IO.MemoryStream.InternalReadInt32() at System.IO.BinaryReader.ReadInt32() at xeno_rat_server.Forms.InfoGrab.DeserializeCookieList(Byte[] bytes) at xeno_rat_server.Forms.InfoGrab.<button3_Click>d__11.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_0(Object state)
> 
> ## ************** Loaded Assemblies **************
> mscorlib
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ## xeno rat server
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Users/attack/Desktop/tools/xeno/xeno%20rat%20server.exe
> ## System.Windows.Forms
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ## System
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ## System.Drawing
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9037.0 built by: NET481REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ## System.Configuration
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9037.0 built by: NET481REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ## System.Core
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ## System.Xml
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9037.0 built by: NET481REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## Accessibility
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9037.0 built by: NET481REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ## MaxMind.GeoIP2
> Assembly Version: 4.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Users/attack/Desktop/tools/xeno/xeno%20rat%20server.exe
> ## netstandard
> Assembly Version: 2.0.0.0
> Win32 Version: 4.8.9037.0
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
> ## MaxMind.Db
> Assembly Version: 4.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Users/attack/Desktop/tools/xeno/xeno%20rat%20server.exe
> ## Newtonsoft.Json
> Assembly Version: 13.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///C:/Users/attack/Desktop/tools/xeno/xeno%20rat%20server.exe
> ## System.Numerics
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9037.0 built by: NET481REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ## System.Runtime.Serialization
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ## System.Data
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ## Anonymously Hosted DynamicMethods Assembly
> Assembly Version: 0.0.0.0
> Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ## System.IO.Compression
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.9037.0 built by: NET481REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
> ************** JIT Debugging ************** To enable just-in-time (JIT) debugging, the .config file for this application or computer (machine.config) must have the jitDebugging value set in the system.windows.forms section. The application must also be compiled with debugging enabled.
> 
> For example:
> 
> When JIT debugging is enabled, any unhandled exception will be sent to the JIT debugger registered on the computer rather than be handled by this dialog box.

have you figured this out?

**Comment by NFS11** [comment]
possibly an av issue where av has detected it.

**Comment by cipiripi84** [comment]
> possibly an av issue where av has detected it.

In my case regarding INFO GRAB, I am able to grab the History and grab the downloads but Passwords I am getting the error above. AV is off defender off realtime protection off..

**Comment by NFS11** [comment]
@cipiripi84 then im not sure what's up with that
